### ISSUE TITLE
Document potential error message and workaround

### ISSUE THREAD

**Issue by wirehead** [documentationjs/dev-documentation#7]
I received the following stack trace:

```
wirehead@vbox:~/src/rm3/lib$ dev-documentation front.js --no
open http://localhost:8000/ in your browser
 info documentation: livereload running on 35729
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at createFsWatchInstance (/usr/lib/node_modules/dev-documentation/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/dev-documentation/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/dev-documentation/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleDir (/usr/lib/node_modules/dev-documentation/node_modules/chokidar/lib/nodefs-handler.js:403:23)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/dev-documentation/node_modules/chokidar/lib/nodefs-handler.js:450:19)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/dev-documentation/node_modules/chokidar/lib/nodefs-handler.js:455:16)
    at FSReqWrap.oncomplete (fs.js:95:15)
```

As it turns out, this is because the limit of watchable files is too low on my particular Ubuntu setup.  

[StackOverflow has a quick answer](http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc).  This should probably be added to the README so the next user who comes along with this issue can get a faster solution.

**Comment by tmcw** [comment]
Moved to main repo
